[2021-12-31 00:21:47,118] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2021-12-25T09:00:00+00:00 [queued]>
[2021-12-31 00:21:47,139] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2021-12-25T09:00:00+00:00 [queued]>
[2021-12-31 00:21:47,139] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 00:21:47,139] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2021-12-31 00:21:47,139] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 00:21:47,148] {taskinstance.py:901} INFO - Executing <Task(TwitterOperator): twitter_aluraonline> on 2021-12-25T09:00:00+00:00
[2021-12-31 00:21:47,151] {standard_task_runner.py:54} INFO - Started process 14921 to run task
[2021-12-31 00:21:47,201] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'twitter_dag', 'twitter_aluraonline', '2021-12-25T09:00:00+00:00', '--job_id', '34', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/twitter_dag.py', '--cfg_path', '/var/folders/yv/xtbkkbn565j6hhnrh5chcn4r0000gn/T/tmpk2h13dvf']
[2021-12-31 00:21:47,203] {standard_task_runner.py:78} INFO - Job 34: Subtask twitter_aluraonline
[2021-12-31 00:21:52,244] {logging_mixin.py:112} INFO - Running <TaskInstance: twitter_dag.twitter_aluraonline 2021-12-25T09:00:00+00:00 [running]> on host MacBook-Pro-de-Roberto.local
[2021-12-31 00:21:57,337] {base_hook.py:89} INFO - Using connection to: id: twitter_default. Host: https://api.twitter.com, Port: None, Schema: None, Login: None, Password: None, extra: XXXXXXXX
[2021-12-31 00:21:57,341] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2021-12-25T09:00:00.00Z&end_time=2021-12-26T09:00:00.00Z
[2021-12-31 00:21:59,568] {logging_mixin.py:112} WARNING - /Users/roberto-almeida/datapipeline/.env/lib/python3.7/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.twitter.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
[2021-12-31 00:21:59,825] {logging_mixin.py:112} INFO - /Users/roberto-almeida/datapipeline/datalake/bronze/twitter_aluraonline/extract_date=2021-12-25/AluraOnline_20211225.json
[2021-12-31 00:21:59,838] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=twitter_dag, task_id=twitter_aluraonline, execution_date=20211225T090000, start_date=20211231T032147, end_date=20211231T032159
[2021-12-31 00:22:02,221] {local_task_job.py:102} INFO - Task exited with return code 0
